import Box from '@mui/material/Box'
import Container from '@mui/material/Container'
import Divider from '@mui/material/Divider'
import Link from '@mui/material/Link'
import Typography from '@mui/material/Typography'

const LAST_UPDATED = 'March 2026'

export function TermsPage() {
  return (
    <Container maxWidth="md" sx={{ py: { xs: 4, md: 8 } }}>
      <Typography variant="h4" gutterBottom>Terms of Service</Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 4 }}>
        Last updated: {LAST_UPDATED}
      </Typography>

      <Section title="Acceptance of terms">
        By accessing or using FightMyBill ("the Service"), you agree to be bound by these
        Terms of Service. If you do not agree to these terms, do not use the Service.
      </Section>

      <Section title="Nature of the Service — important disclaimer">
        <strong>
          FightMyBill is an informational tool only. It does not provide legal advice, medical
          advice, or professional billing consultation.
        </strong>
        <br /><br />
        The analysis generated by the Service is produced by an AI model trained on publicly
        available medical billing standards. It is intended to help you understand your bill
        and prepare questions for your provider's billing department. It is not a substitute
        for advice from a licensed attorney, certified professional coder, or medical billing
        advocate.
        <br /><br />
        We make no guarantee that the analysis is accurate, complete, or applicable to your
        specific situation. Billing rules vary by payer, state, and contract, and the AI may
        not have access to all relevant information about your coverage.
      </Section>

      <Section title="No guarantees of outcome">
        Using the Service and sending a negotiation letter does not guarantee that your
        provider will reduce or correct your bill. FightMyBill is not responsible for any
        outcome resulting from your use of the analysis or negotiation letter, including but
        not limited to: billing disputes, collections activity, damage to credit, or changes
        to your insurance coverage or standing.
      </Section>

      <Section title="Permitted use">
        You may use the Service to analyze your own medical bills or bills for which you have
        legal authority to act (such as for a minor child or a person for whom you hold power
        of attorney). You may not use the Service to:
        <ul style={{ paddingLeft: 20, lineHeight: 2 }}>
          <li>Analyze bills you do not have authorization to access</li>
          <li>Submit false or misleading billing data</li>
          <li>Attempt to circumvent rate limits or payment requirements through automated means</li>
          <li>Resell, redistribute, or reproduce analysis results commercially without permission</li>
        </ul>
      </Section>

      <Section title="Payments and refunds">
        All payments are processed through Stripe. Single-bill analyses and bill pack credits
        are non-refundable once the analysis has been delivered. If you experience a technical
        error that prevents delivery of your analysis, contact us and we will review the
        situation. Bill pack credits expire 12 months after purchase and are not refundable
        after expiry.
      </Section>

      <Section title="Intellectual property">
        The negotiation letter and analysis output generated for your bill are provided for
        your personal use. You may send the letter to your provider's billing department,
        share it with your attorney, or use it for your own insurance appeals. You may not
        sell or commercially license analysis outputs generated by the Service.
      </Section>

      <Section title="Limitation of liability">
        To the maximum extent permitted by applicable law, FightMyBill and its operators shall
        not be liable for any indirect, incidental, special, consequential, or punitive
        damages, including loss of money, health coverage, or any other damages arising out of
        your use of the Service, even if we have been advised of the possibility of such
        damages.
        <br /><br />
        Our total liability to you for any claim arising from use of the Service shall not
        exceed the amount you paid for the specific analysis in dispute.
      </Section>

      <Section title="Governing law">
        These terms are governed by the laws of the United States. Any disputes shall be
        resolved through binding arbitration or in the courts of the applicable jurisdiction,
        as required by law.
      </Section>

      <Section title="Changes to these terms">
        We may update these terms as the Service evolves. We will update the "Last updated"
        date above. Continued use of the Service after changes constitutes acceptance of the
        revised terms.
      </Section>

      <Section title="Contact">
        Questions about these terms can be directed to{' '}
        <Link href="mailto:sbullocks@gmail.com">sbullocks@gmail.com</Link>.
      </Section>
    </Container>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Box sx={{ mb: 4 }}>
      <Typography variant="h6" gutterBottom>{title}</Typography>
      <Divider sx={{ mb: 2 }} />
      <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.9 }}>
        {children}
      </Typography>
    </Box>
  )
}
